config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root 'tops#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  delete 'log_out', to: 'sessions#destroy', as: 'log_out'
  get 'privacy_policy', to: 'tops#privacy_policy'
  get 'terms_of_service', to: 'tops#terms_of_service'
  
  resources :teams do
    resource :attendance, only: %i[create destroy], module: :teams
    member do
      get 'member_page'
    end
    resources :timers, only: %i[new create update] do
      get 'edit_all_timestamps', on: :member
      patch 'update_all_timestamps', on: :member
      resources :break_times, only: %i[create update]
    end
    resource :room, only: %i[show]
  end

  resources :sessions, only: %i[create destroy]
  resource :profile, only: %i[show edit update]

  resources :users, only: %i[show]
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :check_logged_in, only: %i[index privacy_policy terms_of_service]
  include BackgroundImagesConcern
  before_action :set_background_images, only: [:index]

  def index
    # 最後に参加したチームを取得するロジック
    return unless logged_in?
    @active_team = current_user.attend_teams.where('start_date <= ? AND end_date >= ?', Time.current, Time.current).order(:end_date).last
    return if @active_team.present?
    @previous_team = current_user.attend_teams.where('end_date < ?', Time.current).order(:end_date).last
  end

  def privacy_policy; end

  def terms_of_service; end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/index.html.erb
<div class="hero min-h-screen" data-controller="background" data-background-images-value="<%= @images.map { |img| asset_path("top_pages/#{img}") }.to_json %>">
  <div class="hero-overlay bg-opacity-25"></div>
  <div class="hero-content text-center text-base-200">
    <div class="max-w-2xl">
      <h1 class="md:text-5xl sm:text-3xl font-bold text-shadow">ようこそ、やる気の森へ!</h1>
      <p class="py-6 xl:text-lg sp:text-sm text-shadow">仲間と一緒に学習をして「森林」を増やして絶滅危惧種を救おう！</p>
      <div class="flex justify-center gap-x-16">
        <%= link_to '仲間を見つける', teams_path, class: 'btn btn-primary' %>
        <% if logged_in? && @active_team.present? %>
          <%= link_to '森林を増やす', member_page_team_path(@active_team), class: 'btn btn-secondary' %>
        <% elsif logged_in? && @previous_team.present? %>
          <%= link_to '森林を増やす', member_page_team_path(@previous_team), class: 'btn btn-secondary'%>
        <% end %>
      </div>  
    </div>
  </div>
</div>

app/views/tops/privacy_policy.html.erb
<div class="min-h-screen bg-base-100">
  <%= content_for(:title, t('.title')) %>
  <p class="text-2xl sm:text-4xl text-center py-5 sm:py-10 font-bold text-stone-600"> <%= t('.title') %> </p>
    <div class="mx-auto w-full sm:w-[600px]">
      <div class="p-4 sm:p-6">
        <p class="text-xl sm:text-2xl mt-4 sm:mt-6">お客様から取得する情報</p>
        <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">当方は、お客様から以下の情報を取得します。</p>
          <ul class="mt-3 sm:mt-6 space-y-2 pl-5 sm:pl-20 list-disc text-sm sm:text-base">
            <li>氏名(ニックネームやペンネームも含む)</li>
            <li>メールアドレス</li>
            <li>写真や動画</li>
            <li>外部サービスでお客様が利用するID、その他外部サービスのプライバシー設定によりお客様が連携先に開示を認めた情報</li>
            <li>Cookie(クッキー)を用いて生成された識別情報</li>
            <li>OSが生成するID、端末の種類、端末識別子等のお客様が利用するOSや端末に関する情報</li>
            <li>当ウェブサイトの滞在時間、入力履歴、購買履歴等の当ウェブサイトにおけるお客様の行動履歴</li>
            <li>お客様の位置情報</li>
            <li>当アプリの起動時間、入力履歴、購買履歴等の当アプリの利用履歴</li>
          </ul>
          <br>
          <p class="text-xl sm:text-2xl mt-4 sm:mt-6">お客様の情報を利用する目的</p>
          <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">当方は、お客様から取得した情報を、以下の目的のために利用します。</p>
          <p class="text-xl sm:text-2xl mt-4 sm:mt-6">
          <ul class="mt-3 sm:mt-6 space-y-2 pl-5 sm:pl-20 list-disc text-sm sm:text-base">
            <li>当サービスに関する登録の受付、お客様の本人確認、認証のため</li>
            <li>お客様の当サービスの利用履歴を管理するため</li>
            <li>当サービスにおけるお客様の行動履歴を分析し、当サービスの維持改善に役立てるため</li>
            <li>お客様からのお問い合わせに対応するため</li>
            <li>当方の規約や法令に違反する行為に対応するため</li>
            <li>当サービスの変更、提供中止、終了、契約解除をご連絡するため</li>
            <li>当規約の変更等を通知するため</li>
            <li>以上の他、当サービスの提供、維持、保護及び改善のため</li>
          </ul>
          <br>
          <p class="text-xl sm:text-2xl mt-4 sm:mt-6">安全管理のために講じた措置</p>
          <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">当方が、お客様から取得した情報に関して安全管理のために講じた措置につきましては、末尾記載のお問い合わせ先にご連絡をいただきましたら、法令の定めに従い個別にご回答させていただきます。</p>
          <br>
          <p class="text-xl sm:text-2xl mt-4 sm:mt-6">第三者提供</p>
          <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">当方は、お客様から取得する情報のうち、個人データ（個人情報保護法第１６条第３項）に該当するものついては、あらかじめお客様の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。</p>
          <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">但し、次の場合は除きます。</p>
          <ul class="mt-3 sm:mt-6 space-y-2 pl-5 sm:pl-20 list-disc text-sm sm:text-base">
            <li>個人データの取扱いを外部に委託する場合</li>
            <li>当方や当サービスが買収された場合</li>
            <li>事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</li>
            <li>その他、法律によって合法的に第三者提供が許されている場合</li>
          </ul>
          <br>
          <p class="text-xl sm:text-2xl mt-4 sm:mt-6">アクセス解析ツール</p>
          <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">当方は、お客様のアクセス解析のために、「Googleアナリティクス」を利用しています。<br>
            Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。<br>
            トラフィックデータは匿名で収集されており、個人を特定するものではありません。<br>
            Cookieを無効にすれば、これらの情報の収集を拒否することができます。<br>
            詳しくはお使いのブラウザの設定をご確認ください。<br>
            Googleアナリティクスについて、詳しくはGoogleアナリティクスにてご確認ください。</p>
          <br>
          <p class="text-xl sm:text-2xl mt-4 sm:mt-6">プライバシーポリシーの変更</p>
          <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">当方は、必要に応じて、このプライバシーポリシーの内容を変更します。<br>
            この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。</p>
          <br>
          <p class="text-xl sm:text-2xl mt-4 sm:mt-6">お問い合わせ</p>
          <p>お客様の情報の開示、情報の訂正、利用停止、削除をご希望の場合は、<a href="https://forms.gle/Dd7kMXyoSyrNATuq6" class="btn btn-link">お問い合わせフォーム</a> よりご連絡ください。</p>
          <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">この場合、必ず、運転免許証のご提示等当方が指定する方法により、ご本人からのご請求であることの確認をさせていただきます。<br>
            なお、情報の開示請求については、開示の有無に関わらず、ご申請時に一件あたり1,000円の事務手数料を申し受けます。</p>
          <br>
          <p class="text-center mt-5 sm:mt-10 text-sm sm:text-base">2024年2月1日 制定</p>
      </div>
    </div>
</div>