config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root 'tops#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  delete 'log_out', to: 'sessions#destroy', as: 'log_out'
  get 'privacy_policy', to: 'tops#privacy_policy'
  get 'terms_of_service', to: 'tops#terms_of_service'
  
  resources :teams do
    resource :attendance, only: %i[create destroy], module: :teams
    member do
      get 'member_page'
    end
    resources :timers, only: %i[new create update] do
      get 'edit_all_timestamps', on: :member
      patch 'update_all_timestamps', on: :member
      resources :break_times, only: %i[create update]
    end
    resource :room, only: %i[show]
  end

  resources :sessions, only: %i[create destroy]
  resource :profile, only: %i[show edit update]

  resources :users, only: %i[show]
end

app/views/shared/_errors_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer items-center p-4 bg-base-300">
  <aside class="items-center grid-flow-col">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
    <path stroke-linecap="round" stroke-linejoin="round" d="M12 12.75c1.148 0 2.278.08 3.383.237 1.037.146 1.866.966 1.866 2.013 0 3.728-2.35 6.75-5.25 6.75S6.75 18.728 6.75 15c0-1.046.83-1.867 1.866-2.013A24.204 24.204 0 0112 12.75zm0 0c2.883 0 5.647.508 8.207 1.44a23.91 23.91 0 01-1.152 6.06M12 12.75c-2.883 0-5.647.508-8.208 1.44.125 2.104.52 4.136 1.153 6.06M12 12.75a2.25 2.25 0 002.248-2.354M12 12.75a2.25 2.25 0 01-2.248-2.354M12 8.25c.995 0 1.971-.08 2.922-.236.403-.066.74-.358.795-.762a3.778 3.778 0 00-.399-2.25M12 8.25c-.995 0-1.97-.08-2.922-.236-.402-.066-.74-.358-.795-.762a3.734 3.734 0 01.4-2.253M12 8.25a2.25 2.25 0 00-2.248 2.146M12 8.25a2.25 2.25 0 012.248 2.146M8.683 5a6.032 6.032 0 01-1.155-1.002c.07-.63.27-1.222.574-1.747m.581 2.749A3.75 3.75 0 0115.318 5m0 0c.427-.283.815-.62 1.155-.999a4.471 4.471 0 00-.575-1.752M4.921 6a24.048 24.048 0 00-.392 3.314c1.668.546 3.416.914 5.223 1.082M19.08 6c.205 1.08.337 2.187.392 3.314a23.882 23.882 0 01-5.223 1.082" /></svg>
    <p>© 2024 - yaruki morimori!</p>
  </aside> 
  <nav class="grid-flow-col gap-4 md:place-self-center md:justify-self-end mr-4">
    <div class="tooltip tooltip-top" data-tip="利用規約">
      <%= link_to terms_of_service_path, class: "btn btn-ghost btn-circle" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" /></svg>
      <% end %>
    </div>
    <div class="tooltip tooltip-top" data-tip="プライバシーポリシー">
      <%= link_to privacy_policy_path, class: "btn btn-ghost btn-circle" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" /></svg>
      <% end %>
    </div>
    <div class="tooltip tooltip-top" data-tip="お問い合わせ">
      <%= link_to "https://forms.gle/i1vX9zp3E52zzV3z6", class: "btn btn-ghost btn-circle" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155" /></svg>
      <% end %> 
    </div>
  </nav>
</footer>

app/views/shared/_header.html.erb
<div class="navbar bg-base-100">
  <div class="navbar-start">
    <div class="tooltip tooltip-bottom" data-tip="トップページ">
      <%= button_to root_path, class: "btn btn-ghost text-xl", method: :get do %>
        <%= image_tag 'yarumori_logo.png' %> 
      <% end %>
    </div>
  </div>
  <div class="navbar-end mr-4">
    <% if logged_in? %>
      <div class="tooltip tooltip-bottom" data-tip="使いかた">
        <button class="btn btn-ghost btn-circle" onclick="my_modal_4.showModal()">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9.879 7.519c1.171-1.025 3.071-1.025 4.242 0 1.172 1.025 1.172 2.687 0 3.712-.203.179-.43.326-.67.442-.745.361-1.45.999-1.45 1.827v.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 5.25h.008v.008H12v-.008Z" />
          </svg>
        </button>
        <%= render 'shared/usage' %> 
      </div>
      <div class="tooltip tooltip-bottom" data-tip="プロフィール">
        <%= button_to profile_path, class: "btn btn-ghost btn-circle", method: :get do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
        <% end %>
      </div>
      <div class="tooltip tooltip-bottom" data-tip="ログアウト">
        <%= button_to log_out_path, class: "btn btn-ghost btn-circle", method: :delete, data: { turbo: false } do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15m3 0l3-3m0 0l-3-3m3 3H9" /></svg>
        <% end %>
      </div>
    <% else %>       
      <div class="tooltip tooltip-bottom" data-tip="使いかた">
        <button class="btn btn-ghost btn-circle blink" onclick="my_modal_4.showModal()">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9.879 7.519c1.171-1.025 3.071-1.025 4.242 0 1.172 1.025 1.172 2.687 0 3.712-.203.179-.43.326-.67.442-.745.361-1.45.999-1.45 1.827v.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 5.25h.008v.008H12v-.008Z" />
          </svg>
        </button>
        <%= render 'shared/usage' %> 
      </div>
      <div class="tooltip tooltip-bottom" data-tip="ログイン">
        <%= button_to "/auth/github", class: "btn btn-ghost btn-circle", method: :post,  data: { turbo: false } do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75" /></svg>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_usage.html.erb
<dialog id="my_modal_4" class="modal">
  <div class="card md:w-3/5  sm:w-5/6 md:h-5/6 sm:h-60 bg-base-100 shadow-xl">
    <div class="card-body">
      <div class="carousel w-full md:h-5/6 sm:h-5/6">
        <div id="slide1" class="carousel-item relative w-full">
          <%= image_tag "usage-image01.webp", class: "w-full" %> 
          <div class="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
            <a href="#slide4" class="btn btn-circle btn-ghost">❮</a> 
            <a href="#slide2" class="btn btn-circle btn-ghost">❯</a>
          </div>
        </div> 
        <div id="slide2" class="carousel-item relative w-full">
          <%= image_tag "usage-image02.webp", class: "w-full" %> 
          <div class="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
            <a href="#slide1" class="btn btn-circle btn-ghost">❮</a> 
            <a href="#slide3" class="btn btn-circle btn-ghost">❯</a>
          </div>
        </div> 
        <div id="slide3" class="carousel-item relative w-full">
          <%= image_tag "usage-image03.gif", class: "w-full" %> 
          <div class="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
            <a href="#slide2" class="btn btn-circle btn-ghost">❮</a> 
            <a href="#slide4" class="btn btn-circle btn-ghost">❯</a>
          </div>
        </div> 
        <div id="slide4" class="carousel-item relative w-full">
          <%= image_tag "usage-image04.webp", class: "w-full" %> 
          <div class="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
            <a href="#slide3" class="btn btn-circle btn-ghost">❮</a> 
            <a href="#slide5" class="btn btn-circle btn-ghost">❯</a>
          </div>
        </div>
        <div id="slide5" class="carousel-item relative w-full">
          <%= image_tag "usage-image05.gif", class: "w-full" %> 
          <div class="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
            <a href="#slide4" class="btn btn-circle btn-ghost">❮</a> 
            <a href="#slide6" class="btn btn-circle btn-ghost">❯</a>
          </div>
        </div>
        <div id="slide6" class="carousel-item relative w-full">
          <%= image_tag "usage-image06.webp", class: "w-full" %> 
          <div class="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
            <a href="#slide5" class="btn btn-circle btn-ghost">❮</a> 
            <a href="#slide1" class="btn btn-circle btn-ghost">❯</a>
          </div>
        </div>
      </div>
        <div class="card-actions justify-end">
        <form method="dialog">
          <!-- if there is a button, it will close the modal -->
          <button class="md:btn sm:btn btn-sm">オッケー</button>
        </form>
      </div>
    </div>
  </div>
</dialog>