config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root 'tops#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  delete 'log_out', to: 'sessions#destroy', as: 'log_out'
  get 'privacy_policy', to: 'tops#privacy_policy'
  get 'terms_of_service', to: 'tops#terms_of_service'
  
  resources :teams do
    resource :attendance, only: %i[create destroy], module: :teams
    member do
      get 'member_page'
    end
    resources :timers, only: %i[new create update] do
      get 'edit_all_timestamps', on: :member
      patch 'update_all_timestamps', on: :member
      resources :break_times, only: %i[create update]
    end
    resource :room, only: %i[show]
  end

  resources :sessions, only: %i[create destroy]
  resource :profile, only: %i[show edit update]

  resources :users, only: %i[show]
end

app/models/timer.rb
class Timer < ApplicationRecord
  belongs_to :user
  belongs_to :team
  has_many :break_times, dependent: :destroy

  validate :start_time_past
  validate :end_time_past

  def calculated_time
    duration = end_time ? end_time - start_time : 0

    # 休憩時間を差し引く
    total_break_time = break_times.sum do |break_time|
      break_time.break_end_time ? break_time.break_end_time - break_time.break_start_time : 0
    end
    duration - total_break_time
  end

  private

  def start_time_past
    if start_time.present? && start_time > Time.current
      errors.add(:start_time, "は現在時刻より過去である必要があります")
    end
  end

  def end_time_past
    if end_time.present? && start_time.present? && end_time <= start_time
      errors.add(:end_time, "は開始時刻より後である必要があります")
    end

    if end_time.present? && end_time > Time.current
      errors.add(:end_time, "は現在時刻より過去である必要があります")
    end
  end
end

app/controllers/timers_controller.rb
class TimersController < ApplicationController
  before_action :set_team
  before_action :set_timer, only: %i[edit_all_timestamps update_all_timestamps]

  def new
    @timer = Timer.new
  end

  # POST /timers/start
  def create
    @timer = @team.timers.create(user: current_user, start_time: Time.current)
    if @timer.persisted?
      render json: { timer: @timer, timerId: @timer.id }, status: :ok
    else
      render json: { errors: @timer.errors.full_messages }, status: :unprocessable_entity
    end
  end

  # POST /timers/stop
  def update
    @timer = @team.timers.find(params[:id])
    if @timer.update(user: current_user, end_time: Time.current)
      render json: { timer: @timer, calculated_time: @timer.calculated_time, persisted: @timer.persisted? }, status: :ok
    else
      render json: @timer.errors, status: :unprocessable_entity
    end
  end

  def edit_all_timestamps
  end

  def update_all_timestamps

    # Timerの時刻を更新
    start_time = Time.zone.local(*params[:timer].values_at('start_time(1i)', 'start_time(2i)', 'start_time(3i)', 'start_time(4i)', 'start_time(5i)'))
    end_time = Time.zone.local(*params[:timer].values_at('end_time(1i)', 'end_time(2i)', 'end_time(3i)', 'end_time(4i)', 'end_time(5i)'))
    @timer.start_time = start_time
    @timer.end_time = end_time
    save_success = @timer.save

    # break_timeが存在するかどうか確認
    if params[:break_time].present?
      params[:break_time].each do |id, break_time_params|
        break_time = @timer.break_times.find(id)

        # break_timeの時刻を更新
        break_start_time = Time.zone.local(*break_time_params.values_at('break_start_time(1i)', 'break_start_time(2i)', 'break_start_time(3i)', 'break_start_time(4i)', 'start_time(5i)').map(&:to_i))
        break_end_time = Time.zone.local(*break_time_params.values_at('break_end_time(1i)', 'break_end_time(2i)', 'break_end_time(3i)', 'break_end_time(4i)', 'break_end_time(5i)').map(&:to_i))
        break_time.break_start_time = break_start_time
        break_time.break_end_time = break_end_time
        save_success &= break_time.save
      end
    end

    if save_success 
      render json: { status: "success", calculated_time: @timer.calculated_time }, status: :ok
    else
      render json: { status: "error", errors: @timer.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def set_team
    @team = Team.find(params[:team_id])
    return if @team.user == current_user || @team.attendees.include?(current_user)

    redirect_to root_path, alert: t('defaults.message.not_authority')
  end

  def set_timer
    @timer = Timer.find(params[:id])
  end
end

app/helpers/timers_helper.rb
module TimersHelper
end

app/views/timers/_edit_modal.html.erb
<div
  data-edit-timer-target="modal"
  class="hidden bg-gray-300 bg-opacity-50 fixed inset-0 overflow-y-auto flex items-center justify-center"
  style="z-index: 9999;">
  <div class="max-h-screen md:w-1/2 sm:w-72 max-w-2lg relative">
    <div class="bg-white shadow-xl rounded-lg">
      <div class="flex justify-end">
        <div class="tooltip tooltip-left"  data-tip="学習計測へ">
          <%= link_to new_team_timer_path(@team), class: "btn btn-sm btn-circle btn-ghost m-2" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
            </svg>
          <% end %>
        </div>
      </div>
      <div class="p-8">
        <h2 class="text-xl mb-4">編集後の学習時間</h2>
        <p class="mb-4"><span data-edit-timer-target="modalTime"></span></p>
        <div class="flex justify-end items-center flex-wrap mt-6">
          <%= link_to "#", class: "btn btn-primary mx-2", target: '_blank', data: { edit_timer_target: "shareLink" } do %>
            <%= image_tag ("logo-black.png"), size: "20x20" %> シェア！
          <% end %>
          <%= link_to "森林を確認", member_page_team_path(@team), class: "btn btn-secondary m-2" %>
          <button class="btn btn-accent mx-2" data-action="click->edit-timer#modalClose">
            編集し直す 
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/timers/_modal.html.erb
<div
  data-timer-target="modal"
  class="hidden bg-gray-300 bg-opacity-50 fixed inset-0 overflow-y-auto flex items-center justify-center"
  style="z-index: 9999;">
  <div class="max-h-screen md:w-1/2 sm:w-72 max-w-2lg relative">
    <div class="bg-white shadow-xl rounded-lg">
      <div class="flex justify-end">
        <div class="tooltip tooltip-left"  data-tip="学習計測へ">
          <%= link_to new_team_timer_path(@team), class: "btn btn-sm btn-circle btn-ghost m-2" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
            </svg>
          <% end %>
        </div>
      </div>
      <div class="pb-8 px-8">
        <h2 class="text-xl mb-4">学習時間</h2>
        <p class="mb-4"><span data-timer-target="modalTime"></span></p>
        <div class="flex justify-end items-center flex-wrap mt-6" id="modal-button">
          <%= link_to "#", class: "btn btn-primary mx-2", target: '_blank', data: { timer_target: "shareLink" } do %>
            <%= image_tag ("logo-black.png"), size: "20x20" %> シェア！
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/timers/_start_modal.html.erb
<div
  data-timer-target="bg" 
  class="hidden bg-gray-300 bg-opacity-50 fixed inset-0 overflow-y-auto flex items-center justify-center"
  style="z-index: 9999;">
  <div class="max-h-screen md:w-1/2 sm:w-64 max-w-2lg relative">
    <div class="bg-white shadow-xl rounded-lg">
      <div class="p-8">
        <h2 class="md:text-2xl sm:text-xl md:divider divider-info mb-8">学習タイマーご利用の注意点！</h2>
        <li class="my-4">ページの再読み込み（リロード）をすると計測できなくなります…（最重要！）</p>
        <li class="mb-4">PCがスリープ状態になるとタイマー表示が正確ではなくなってしまいます… <br>（計測はできます）</p>
        <li class="mb-4">PCを離れる場合は"ちょっと休憩"ボタンをタイマーを止めることをオススメします！<br>（戻ってきたら"休憩おしまい"ボタンを忘れずに！）</p>
        <div class="flex justify-end items-center flex-wrap mt-6">
          <button class="btn btn-accent mx-2" data-action="click->timer#modalClose">
            オッケーわかったよ！ 
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/timers/edit_all_timestamps.html.erb
<div class="min-h-screen bg-base-100">
  <div class="container flex justify-start mx-auto py-4">
    <h1 class="text-2xl"><%= t('.title') %></h1>
  </div>
  <%= form_with model: @timer, url: update_all_timestamps_team_timer_path(team_id: @team.id, id: @timer.id),
    local: false, data: { turbo: false, controller: "edit-timer", target: "edit-timer.form", action: "submit->edit-timer#submitForm" } do |f| %>
    <%= render 'shared/errors_messages', model: f.object %>
    <div data-edit-timer-target="flashMessage" role="alert" class="hidden alert"></div>
    <div class="mx-12 my-12 grid grid-cols-2 gap-6 md:justify-items-center sm:justify-center">      
      <div class="card md:w-[32rem] sm:w-[22rem] bg-base-200 shadow-md p-4">
        <div class="mb-10 field">
          <%= f.label :start_time, t(Timer.human_attribute_name(:start_time)), class: 'label mb-0 text-lg font-semibold text-gray-700' %>
          <%= f.datetime_select :start_time, class: 'select select-success w-full max-w-md' %>
        </div>

        <div class="mb-10 field">
          <%= f.label :end_time, t(Timer.human_attribute_name(:end_time)), class: 'label mb-0 text-lg font-semibold text-gray-700' %>
          <%= f.datetime_select :end_time, class: 'select select-success w-full max-w-md' %>
        </div>
      </div>

      <% if @timer.break_times.any? %>
        <div class="card md:w-[32rem] sm:w-[22rem] bg-base-200 shadow-md p-4">
          <% @timer.break_times.each_with_index do |break_time, index| %>
            <%= fields_for "break_time[#{break_time.id}]", break_time do |bf| %>
              <div class="mb-10 field">
                <%= bf.label :break_start_time, "休憩開始時間 #{index + 1}", class: 'label mb-0 text-lg font-semibold text-gray-700' %>
                <%= bf.datetime_select :break_start_time, class: 'select select-success w-full max-w-xs' %>
              </div>
              <div class="mb-10 field">
                <%= bf.label :break_end_time, "休憩終了時間 #{index + 1}", class: 'label mb-0 text-lg font-semibold text-gray-700' %>
                <%= bf.datetime_select :break_end_time, class: 'select select-success w-full max-w-xs' %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="mx-28 flex justify-end py-4">
      <%= f.submit t('defaults.register'), class: 'btn btn-primary' %>
    </div>
    <%= render partial: 'timers/edit_modal', team: @team, timer: @timer %>
  <% end %>
</div>

app/views/timers/new.html.erb
<div data-controller="timer" 
     data-timer-team-id-value="<%= @team.id %>" 
     data-timer-timer-id-value="<%= @timer.id %>" 
     <% if @break_time.present? %>
       data-timer-break-time-id-value="<%= @break_time.id %>"
     <% end %>>
  <%= render partial: 'timers/start_modal' %>
  <%= render partial: 'timers/modal' %>
  <div data-timer-target="flashMessage" role="alert" class="hidden alert"></div>
 
  <div class="flex justify-center items-center min-h-screen bg-base-100">
    <div class="text-center">
      <div class="grid grid-flow-col gap-5 text-center auto-cols-max">
        <div class="flex flex-col">
          <span class="font-mono text-8xl">
            <span data-timer-target="hours">00</span>
          </span>
          時間 
        </div> 
        <div class="flex flex-col">
          <span class="font-mono text-8xl">
            <span data-timer-target="minutes">00</span>
          </span>
          分
        </div>
        <div class="flex flex-col">
          <span class="font-mono text-8xl">
            <span data-timer-target="seconds">00</span>
          </span>
          秒 
        </div>
      </div>
          
      <!-- ストップウォッチのコントロールボタン -->
      <div class="flex justify-center mt-10">
        <%= button_tag type: 'button', data: { action: "click->timer#start" }, class: "btn btn-primary mx-2", id: "start-button" do %>
          はじめる
        <% end %>
        <%= button_tag type: 'button', data: { action: "click->timer#togglePauseResume", timer_target: "pauseResumeButton"}, class: "btn btn-secondary mx-2", id: "pause-resume-button" do %>
          ちょっと休憩 
        <% end %>
        <%= button_tag type: 'button', data: { action: "click->timer#end click->timer#modalOpen" }, class: "btn btn-accent mx-2" do %>
          おしまい 
        <% end %>
      </div>
    </div>
  </div>
</div>